export const _resumeList: Apis.Resume.Get[] = [
  {
    id: '1',
    applicantName: 'John Doe',
    jobPosition: 'Frontend Developer',
    uploadDate: 1693536000,
    status: 'pending',
    url: './test.pdf',
  },
  {
    id: '2',
    applicantName: 'Jane Smith',
    jobPosition: 'Backend Developer',
    uploadDate: 1693228800,
    status: 'accepted',
    url: './test.pdf',
  },
  {
    id: '3',
    applicantName: 'Michael Johnson',
    jobPosition: 'UI/UX Designer',
    uploadDate: 1693622400,
    status: 'rejected',
    url: './test.pdf',
  },
  {
    id: '4',
    applicantName: 'Emily Davis',
    jobPosition: 'Full Stack Developer',
    uploadDate: 1693708800,
    status: 'pending',
    url: './test.pdf',
  },
  {
    id: '5',
    applicantName: 'Chris Brown',
    jobPosition: 'Data Scientist',
    uploadDate: 1693315200,
    status: 'accepted',
    url: './test.pdf',
  },
];
