export const _resumeList: Apis.Resume.Get[] = [
  {
    id: '1',
    applicantName: '존 스미스',
    jobPosition: '프론트엔드 개발자',
    uploadDate: 1725693536000,
    status: 'pending',
    url: './test.pdf',
  },
  {
    id: '2',
    applicantName: '제인 도우',
    jobPosition: '백엔드 개발자',
    uploadDate: 1722693536000,
    status: 'accepted',
    url: './test.pdf',
  },
  {
    id: '3',
    applicantName: '앨리스 클라크',
    jobPosition: 'UI/UX 디자이너',
    uploadDate: 1724693536000,
    status: 'rejected',
    url: './test.pdf',
  },
  {
    id: '4',
    applicantName: '마이클 존슨',
    jobPosition: '풀스택 개발자',
    uploadDate: 1723993536000,
    status: 'pending',
    url: './test.pdf',
  },
  {
    id: '5',
    applicantName: '크리스 브라운',
    jobPosition: '데이터 엔지니어',
    uploadDate: 1718693536000,
    status: 'accepted',
    url: './test.pdf',
  },
];
